echo "--- 3. Removing Partner/OEM apps ---"
adb shell pm uninstall -k --user 0 com.booking
adb shell pm uninstall -k --user 0 com.amazon.mShop.android.shopping
adb shell pm uninstall -k --user 0 com.amazon.appmanager
adb shell pm uninstall -k --user 0 com.android.bookmarkprovider
adb shell pm uninstall -k --user 0 com.android.partnerbrowsercustomizations.tmobile
adb shell pm uninstall -k --user 0 com.baidu.input_huawei
adb shell pm uninstall -k --user 0 com.android.providers.partnerbookmarks
adb shell pm uninstall -k --user 0 com.android.partnerbrowsercustomizations
adb shell pm uninstall -k --user 0 com.android.stk
adb shell pm uninstall -k --user 0 com.ironsource.appcloud.oobe.huawei
adb shell pm uninstall -k --user 0 com.orange.update
adb shell pm uninstall -k --user 0 com.swiftkey.swiftkeyconfigurator
adb shell pm uninstall -k --user 0 com.microsoft.translator
# Pre-installed Facebook bloatware. Shame on you, Huawei!
adb shell pm uninstall -k --user 0 com.facebook.appmanager
adb shell pm uninstall -k --user 0 com.facebook.services
adb shell pm uninstall -k --user 0 com.facebook.system
adb shell pm uninstall -k --user 0 com.ebay.carrier

echo "--- 4. Removing Huawei apps ---"
adb shell pm  uninstall -k --user 0 com.google.android.googlequicksearchbox
#adb shell pm  uninstall -k --user 0 com.google.android.apps.books
#adb shell pm  uninstall -k --user 0 com.google.android.apps.docs.editors.docs
#adb shell pm  uninstall -k --user 0 com.google.android.apps.docs.editors.sheets
#adb shell pm  uninstall -k --user 0 com.google.android.apps.docs.editors.slides
adb shell pm  uninstall -k --user 0 com.google.android.apps.cloudprint
#adb shell pm  uninstall -k --user 0 com.google.android.apps.docs
#adb shell pm  uninstall -k --user 0 com.google.android.apps.mapps
#adb shell pm  uninstall -k --user 0 com.google.android.apps.photos
adb shell pm  uninstall -k --user 0 com.google.android.apps.tachyon
adb shell pm  uninstall -k --user 0 com.google.android.apps.magazines
adb shell pm  uninstall -k --user 0 com.google.android.feedback
#adb shell pm  uninstall -k --user 0 com.google.android.keep
adb shell pm  uninstall -k --user 0 com.google.android.marvin.talkback
adb shell pm  uninstall -k --user 0 com.google.android.music
adb shell pm  uninstall -k --user 0 com.google.android.play.games
#adb shell pm  uninstall -k --user 0 com.google.android.projection.gearhead
adb shell pm  uninstall -k --user 0 com.google.android.talk
adb shell pm  uninstall -k --user 0 com.google.android.videos
#adb shell pm  uninstall -k --user 0 com.google.android.youtube
adb shell pm  uninstall -k --user 0 com.google.android.googlequicksearchbox
adb shell pm  uninstall -k --user 0 com.amazon.apadb shell pm anager
adb shell pm  uninstall -k --user 0 com.amazon.mShop.android.shopping
adb shell pm  uninstall -k --user 0 com.booking
adb shell pm  uninstall -k --user 0 com.android.email
adb shell pm  uninstall -k --user 0 com.android.bookmarkprovider
#adb shell pm  uninstall -k --user 0 com.android.chrome
#adb shell pm  uninstall -k --user 0 com.android.hwmirror
adb shell pm  uninstall -k --user 0 com.android.partnerbrowsercustomizations.tmobile
adb shell pm  uninstall -k --user 0 com.android.providers.partnerbookmarks
adb shell pm  uninstall -k --user 0 com.android.partnerbrowsercustomizations
#adb shell pm  uninstall -k --user 0 com.android.storagemanager
adb shell pm  uninstall -k --user 0 com.android.stk
adb shell pm  uninstall -k --user 0 com.baidu.input_huawei
adb shell pm  uninstall -k --user 0 com.huawei.apadb shell pm arket
adb shell pm  uninstall -k --user 0 com.huawei.phoneservice
adb shell pm  uninstall -k --user 0 com.huawei.hwid
adb shell pm  uninstall -k --user 0 com.huawei.android.chr
adb shell pm  uninstall -k --user 0 com.huawei.android.hwpay
adb shell pm  uninstall -k --user 0 com.huawei.android.remotecontroller
adb shell pm  uninstall -k --user 0 com.huawei.android.tips
adb shell pm  uninstall -k --user 0 com.huawei.browser
adb shell pm  uninstall -k --user 0 com.huawei.compass
adb shell pm  uninstall -k --user 0 com.huawei.contactscamcard
adb shell pm  uninstall -k --user 0 com.huawei.health
#adb shell pm  uninstall -k --user 0 com.huawei.hwapplet
adb shell pm  uninstall -k --user 0 com.huawei.hifolder
adb shell pm  uninstall -k --user 0 com.huawei.KoBackup
adb shell pm  uninstall -k --user 0 com.huawei.parentcontrol
adb shell pm  uninstall -k --user 0 com.huawei.search
adb shell pm  uninstall -k --user 0 com.huawei.tips
adb shell pm  uninstall -k --user 0 com.huawei.vassistant
adb shell pm  uninstall -k --user 0 com.huawei.wallet
adb shell pm  uninstall -k --user 0 com.huawei.himovie.overseas
adb shell pm  uninstall -k --user 0 com.android.soundrecorder
adb shell pm  uninstall -k --user 0 com.ironsource.appcloud.oobe.huawei
adb shell pm  uninstall -k --user 0 com.facebook.apadb shell pm anager
adb shell pm  uninstall -k --user 0 com.facebook.system
adb shell pm  uninstall -k --user 0 com.facebook.katana
adb shell pm  uninstall -k --user 0 com.facebook.services
adb shell pm  uninstall -k --user 0 com.hicloud.android.clone
adb shell pm  uninstall -k --user 0 com.microsoft.translator
adb shell pm  uninstall -k --user 0 com.swiftkey.swiftkeyconfigurator
adb shell pm  uninstall -k --user 0 com.touchtype.swiftkey
adb shell pm  uninstall -k --user 0 com.example.android.notepad
